add some code to cleanup new user stuff

diff --git a/freshrc b/freshrc
--- a/freshrc
+++ b/freshrc
@@ -1,5 +1,14 @@
 # -*- mode: sh -*-
 
+# clean up files from skel
+for filename in .bashrc .dircolors; do
+    if ! [ -L ~/$filename ] && [ -f ~/$filename ]; then
+	echo "Creating backup of ~/$filename"
+	mv ~/$filename ~/$filename.bak
+    fi
+done
+
+
 fresh freshshell/fresh bin/fresh --bin
 
 fresh jasoncodes/dotfiles bin/gemdiff --bin=~/bin/gem-diff
